# Generated by Django 5.2.10 on 2026-02-11 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfazUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('require_2fa', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso_interfaz', to='users_hub.usuario')),
            ],
        ),
    ]
