# Generated by Django 5.2.10 on 2026-02-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('camara_ip', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoArea',
            fields=[
                ('permiso_id', models.AutoField(primary_key=True, serialize=False)),
                ('puede_acceder', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_log.area')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_hub.rol')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('motivo_denegacion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_registro_path', models.ImageField(upload_to='capturas_acceso/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_log.area')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_hub.usuario')),
            ],
        ),
    ]
