# Generated by Django 5.2.10 on 2026-02-05 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
        ('users_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroacceso',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='permitido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_hub.rol'),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='foto_registro_path',
            field=models.ImageField(blank=True, null=True, upload_to='capturas_acceso/'),
        ),
        migrations.AlterUniqueTogether(
            name='permisoarea',
            unique_together={('rol', 'area')},
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['fecha_hora'], name='audit_log_r_fecha_h_920f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['permitido'], name='audit_log_r_permiti_ccbba2_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['area'], name='audit_log_r_area_id_bcfdb7_idx'),
        ),
    ]
