# Generated by Django 5.2.10 on 2026-03-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_log', '0002_alter_registroacceso_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cámara Entrada Principal', max_length=100)),
                ('hardware_index', models.IntegerField(help_text='Índice USB (0, 1, 2...)', unique=True)),
                ('is_activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='audit_log.area')),
            ],
        ),
    ]
