# Generated by Django 5.2.10 on 2026-02-05 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('camara_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la cámara', max_length=100)),
                ('ip', models.GenericIPAddressField(help_text='IP desde donde se conecta la cámara', unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='audit_log.area')),
            ],
        ),
    ]
