# Generated by Django 5.2.10 on 2026-02-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto_path_base', models.ImageField(upload_to='rostros/entrenamiento/')),
                ('foto_perfil_path', models.ImageField(blank=True, null=True, upload_to='rostros/perfil/')),
                ('face_embedding', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='users_hub.rol')),
            ],
        ),
    ]
