# Generated by Django 5.2.10 on 2026-02-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_path_base',
            field=models.ImageField(blank=True, null=True, upload_to='rostros/entrenamiento/'),
        ),
    ]
